### ISSUE TITLE
Record the last time a user opened the app

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe#101]
Create a new Firebase user property (e.g. lastAppOpen) which updates to current date whenever the app is opened. 

This can then be used to delete users based on a certain time of app inactivity in line with the privacy policy.

Resources:
https://firebase.google.com/docs/analytics/android/properties
https://github.com/firebase/functions-samples/tree/master/delete-unused-accounts-cron

**Comment by jhenshall** [comment]
@laurentS or @Hagellach37 is this one possible before launch?

**Comment by laurentS** [comment]
@jhenshall I think the `lastSignInTime` that you see in https://github.com/firebase/functions-samples/blob/master/delete-unused-accounts-cron/functions/index.js#L64 is actually a standard feature of firebase. Last time I looked into it, the field was available, as google keeps track of it, so there shouldn't be a need to code anything extra. The best way to check would be to modify that function you shared above to not delete users, but just list them out, just to see that it works.

**Comment by laurentS** [comment]
I've created an attribute `lastAppUse` in the user's profile, which is updated every time the app opens on the list of projects. This gives us the last time the user started the app, even if they were already logged in, so it should fit your requirements.
