### ISSUE TITLE
Add imagery source/credits

### ISSUE THREAD

**Issue by cgiovando** [mapswipe/mapswipe#103]
Related to #90, credits need to be added for imagery used in each project. For the specific change detection project type that is using Planet's imagery, we were asked to add `Imagery © 2019 Planet.com` directly in the popup info window.

This text should be parameterized to allow project creators to specify different credits for each project, depending on the imagery sources used.

**Comment by Hagellach37** [comment]
for bing, digital globe etc. it should be not problem, so for all imagery providers that we can provide as defaults.

if the project managers choose a custom tileserver they will need to add it. 

We need to implement this in the import form.

**Comment by laurentS** [comment]
We agreed that the credit string will be stored under `projects/<projectID>/tileServer/credits`.
