### ISSUE TITLE
Convert old user profiles to new format

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#105]
This relates to https://github.com/mapswipe/python-mapswipe-workers/issues/137 but for the app part

**Comment by Hagellach37** [comment]
This works for all projects which use zoom level 18. (All "old" project so far have used this zoom level.)

### Transfer distance to taskContributionCount:
* distancePerTile at zoomlevel 18 = 0.0233732728  (see also https://github.com/mapswipe/mapswipe/blob/9eccda71084b8494e2d0d7756f9cfe957825ec67/src/shared/Database.js#L790)
* `taskContributionCount = distance / 0.0233732728`

### Transfer Badges/Levels
* this is defined here: https://github.com/mapswipe/mapswipe/blob/dev/src/shared/Levels.js
* we need to change `expRequired`
* `expRequired_new = expRequired / 0.0233732728`

**Comment by laurentS** [comment]
for the record, it looks like the new version of the app will require users to relogin, even if they were logged into the app before upgrade (both on Android and iOS).

**Comment by laurentS** [comment]
I've made the app mark converted profiles with `updateNeeded: true` so that finding them in the backend script is easy.
