### ISSUE TITLE
Update login/signup screen with GDPR warnings

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#106]
The signup screen should include
- a warning about how data is used,
- a link to the BRC privacy policy,
- a checkbox for the user to confirm their agreement with it

@jhenshall can you confirm there is nothing else needed? maybe add a link to the mockup you've prepared?

**Comment by laurentS** [comment]
do we need to get "old" accounts to agree to the new policy? @jhenshall ?

**Comment by jhenshall** [comment]
Will check all this with Information Governance and add the screen design here when ready and signed off.

**Comment by jhenshall** [comment]
@laurentS attaching the GDPR compliant version of the sign up screen. The design will change but is it worth getting at least the compliance in app for now? The privacy notice will link to mapswipe.org/privacy but this obviously doesn't exist yet!

![Screen - Sign up](https://user-images.githubusercontent.com/6359748/65160562-dac15e80-da2d-11e9-8219-066ea76d8559.jpg)
