### ISSUE TITLE
Add ruler/scale overlay

### ISSUE THREAD

**Issue by rivermont** [mapswipe/mapswipe#111]
Since some projects have slightly different zoom levels, or because of offset and other imagery quirks it can be hard to tell the scale, I think it would be good to include a small ruler in one of the bottom corners of the viewport. Similar to what the iD editor has:

![image](https://user-images.githubusercontent.com/25139386/64914372-f969e180-d71d-11e9-9f82-ffb3d15c4846.png)

It would be overlayed on top of the tiles, but with transparency. Long-pressing the tile under it wouldn't show the scale on the enlarged image.

**Comment by laurentS** [comment]
Hi @rivermont Thanks for reporting this. I think it would be a duplicate of #46 that is on the [plan for mapswipe 2.0](https://github.com/orgs/mapswipe/projects/2).
I'll let you close if you agree this is duplicate, if not, please clarify what you have in mind!

**Comment by rivermont** [comment]
Yep, definitely a duplicate. My search terms failed to find that one.
I'll copy my suggestions to that issue so they're on the board.
