### ISSUE TITLE
[Micro bug] Email address input field capitalises first letter

### ISSUE THREAD

**Issue by MegaArthur** [mapswipe/mapswipe#121]
The registration/log in input field for email addresses shouldn't capitalise the first letter, the standard is not to, due to most email addresses starting with a lowercase letter (from what I've seen at least)

**Comment by laurentS** [comment]
Good point, the fix is easy, just need to set [this prop](https://facebook.github.io/react-native/docs/textinput.html#autocapitalize) on the input fields.
