### ISSUE TITLE
[UI/UX] App name is not capitalised

### ISSUE THREAD

**Issue by MegaArthur** [mapswipe/mapswipe#122]
The app's name is not capitalised on Android, making it negatively stand out from other apps.

**Comment by laurentS** [comment]
I guess you mean the name shown on the launcher, under the icon? How did I never notice this?

Thanks for reporting!

**Comment by jhenshall** [comment]
This is the same on iOS. Yes, it's the text under the icon on the home screen. I wrongly thought this would be set in the app stores. Can we set all references to the app to have capitalised M and S - MapSwipe. Thanks!
