### ISSUE TITLE
Not displaying all tasks of a group

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/mapswipe#123]
It seems that the app is not displaying all tasks, when the total number of tasks in a group can't be divided by 6. (e.g. there are 3 more tasks to be displayed, which should result in half of my screen having tasks and the other half not showing them). My suspicion is, that if you get a group with let's say 15 tasks, only the first 12 will be displayed and the last 3 are omitted.

For all affected groups, the app doesn't write the results for the last 3 tasks. This has the effect that we are missing results, for which there are tasks. Here's an graphical example:

![Screenshot from 2019-10-01 02-22-06](https://user-images.githubusercontent.com/7045979/65925795-8b4a3d80-e3f2-11e9-8bba-f003abf12aa0.png)

I just double checked firebase. The tasks are in there and also the group attributes seem to be set correctly. So I suspect it will be related to the app side.

**Comment by laurentS** [comment]
This was fixed in v2.0. Closing :)
