### ISSUE TITLE
Button to continue mapping

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe#126]
User has requested a button at the end of a group that enables them to start a new group without going back to the project overview page. It was a feature on the old app.

Detailed designs to follow but perhaps a basic button can be added back in in the meantime so we have 'Continue mapping' and 'Finish mapping'?

**Comment by laurentS** [comment]
Yes, I had to remove the button temporarily because of a bug (see #53). This needs to be put back in, unfortunately #88 makes this a lot harder to debug.

**Comment by jhenshall** [comment]
Thanks @laurentS. Sorry, missed the existing issue so I'll close this one and we can keep #53 open.
