### ISSUE TITLE
'Complete session' button text cutoff on smaller screens

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe#128]
The button text for 'Complete Session' is cutoff on smaller screens. Screenshot attached is from an iPhone SE (I imagine same issue for iPhone 5 and below).

Think new designs will have totally different buttons (which should address this) but in meantime, reduce button font size? Or make button wider?

![MicrosoftTeams-image](https://user-images.githubusercontent.com/6359748/66335482-0059cd80-e933-11e9-9f39-3de8ad42c28d.png)

**Comment by laurentS** [comment]
I suggest we make the button a bit wider for now, that should do for most phones :)

**Comment by laurentS** [comment]
Fixed in `2.0.1(0)`
