### ISSUE TITLE
Back button behaviour on some Android devices

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe#130]
On devices with a dedicated back button, when it is tapped on the Mission overview screen, it goes back to the login page. If clicked again, it goes to a white screen and the app must be restarted.

Normal behaviour seems to be if you cannot navigate further back in the app (which is the case from the mission overview page), the app closes.

**Comment by laurentS** [comment]
good catch! I don't know how we've not picked this up during testing. I've marked it for milestone 2.0.1 :)

**Comment by laurentS** [comment]
Fixed in `2.0.1(0)`
