### ISSUE TITLE
Change the app startup for iOS

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe#133]
The app startup on iOS has a lot of movement with swiping transitions that go from startup splash screen > loading screen > missions overview very quickly. Gif attached, which has been slightly slowed down to show the transition better.

Can we:
1. Change the transition to remove the swipe motion
2. Remove the middle loading screen on app startup so the logo screen is displayed slightly longer and then straight to the missions overview page.

![IMB_KMETYq](https://user-images.githubusercontent.com/6359748/66438174-de8c4380-ea23-11e9-94b8-8a224619e255.GIF)

**Comment by laurentS** [comment]
Fixed in `2.0.1(0)`.
