### ISSUE TITLE
User name might be too long

### ISSUE THREAD

**Issue by Birnbaum2001** [mapswipe/mapswipe#135]
Hi,

A user name might be too long and cause a conflict with the text about the number of completed tasks, see attached screenshot. 

That's an iPhone XS with MapSwipe 2.0.0 (3)
![InkedIMG_8110_LI](https://user-images.githubusercontent.com/7634429/66705872-7479e400-ed2c-11e9-875c-563a54ea2f82.jpg)

Cheers,
Kay

**Comment by laurentS** [comment]
@Birnbaum2001 not sure if you saw it, but the latest `mapswipe dev` build includes your PR for this issue. I think you had been in touch about joining the test team, so you should be able to try it out now via `testflight` :)

**Comment by laurentS** [comment]
@Birnbaum2001 this should now be available in the production release 2.0.2 that just came out. Thanks for your help!
