### ISSUE TITLE
CI always fails on third party pull-requests

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#137]
As encrypted files [are not available on third party PRs](https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions), our test suite cannot build the app at all, so we can't verify the bare minimum on them. We should fix `.travis.yml` so that it can run at least part of the tests on external PR.
See for example https://github.com/mapswipe/mapswipe/pull/136

**Comment by Hagellach37** [comment]
outdated
