### ISSUE TITLE
Progress tracker showing negative counts

### ISSUE THREAD

**Issue by jbergmann91** [mapswipe/mapswipe#141]
Progress tracker showing negative tasks and negative swipes needed to achieve the next level -- reported on October 9. User then emailed back on Oct 17 saying issue resolved itself, but did not update app. (Definitely using version 2.0.0 -- iPhone XR, running iOS 13.1.2)

**Comment by laurentS** [comment]
thanks for the report @jbergmann91 !
did you get details on which level the user was at?

**Comment by jbergmann91** [comment]
Damn, just figured out I could attach screenshots here! Learn something new every.day. @laurentS !
![image0](https://user-images.githubusercontent.com/48020580/67215928-f1b9ee80-f3e7-11e9-879c-5288e5d4f2e0.png)
