### ISSUE TITLE
Difficulties marking tiles as green in Android

### ISSUE THREAD

**Issue by jbergmann91** [mapswipe/mapswipe#147]
I recently installed the app and love the idea. I noticed, however, that the
user interface is not as responsive as it should which creates frustration
in using the app. Specifically, often times when I tap on a tile to mark it
green instead of making it, the app flashes the message that swiping down
marks all tiles as red (it only shows the message without marking anything)
and I need to tap multiple times until the tile is finally marked green.
This seems easy to fix and would make the app so much more enjoyable to use.

1) I have a Pixel (1) phone with Android 10
2) I confirmed that I'm using MapSwipe 2.0 which was last updated Oct 19.
3) Yes, the experience is across all MapSwipe projects.

**Comment by jbergmann91** [comment]
Another user reporting same issue with Samsung Galaxy S8 running Android 9

**Comment by laurentS** [comment]
This should now be working fine. Please reopen if not.
