### ISSUE TITLE
Permalink to latest apk version

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe#149]
**Feature request**
We want to add a link to the website that always directs to the latest version apk. To do that, we need to modify the release process a little to mark beta apps as not being part of the normal releases, so that the permalink ignores them.

**Comment by laurentS** [comment]
@jhenshall this is the link you need https://github.com/mapswipe/mapswipe/releases/latest/download/app-dev-release.apk
it should always point to the latest (non-beta) APK.

**Comment by laurentS** [comment]
I think this is now working. Please reopen if the link above is not working.
