### ISSUE TITLE
Save additional information "group_result" information when users submit their contributions

### ISSUE THREAD

**Issue by mathcass** [mapswipe/mapswipe#15]
Originally submitted by @Hagellach37 

---

When using the MapSwipe app, users work on a group of tasks. However, when uploading their contributions, individual "results" are saved in firebase. Each result consists of information, which refer to a specific task. Information that a group has been completed by a user are not explicitly stored in firebase as a "group_result" or similar things. Regarding groups, the only thing that happens is that the *CompletedCount" of a group is increased. But, no username or timestamp is added in this step. We therefore can't umambigiously match users and the groups they completed. Here's an example for a result:

key | value
-- | --
device | "E2A6ACC2-850A-4192-BF99-00D6F2940889"
id | "18-129743-119918"
item | "BUILDINGS ONLY"
projectId | "13511"
result | 2
timestamp | 1522859450025
user | "c09QHjeOHXPpWliefir5yVKDPyo1"
wkt | ""

To address this issue I propose to save an additional element in firebase: A **group_result**. This would not affect the existing workflow and could be added in parallel to the existing transfer of the results. This element could look like this:

key | value
-- | --
device | "E2A6ACC2-850A-4192-BF99-00D6F2940889"
id | "101"
item | "BUILDINGS ONLY"
projectId | "13512"
results | {...} 
timestamp | 1522859450025
user | "XXXXXXXXXXX"
xMax | "157546"
xMin | "157514"
yMax | "133569"
yMin | "133567"

The *results* attribute could be an additional place, where we could store the result information for this group. 

Adding this new feature would allow us easily derive all contributions of individual users (including "no building" classifications which are not stored in the database), which is an important input to generate more reliable user statistics. Furthermore, we could use the group result to provide feeback to users.

**Comment by laurentS** [comment]
This is fixed with the switch to mapswipe 2 data model.
