### ISSUE TITLE
Add "MissingCount" attribute to groups to address data quality issues

### ISSUE THREAD

**Issue by mathcass** [mapswipe/mapswipe#16]
Originally submitted by @Hagellach37 

---

When loading new tasks in MapSwipe users always request a group of tasks. For each project a user will download the group, which has been completed least. I propose to add another attribute "MissingCount" instead, to download the group, which still needs the most contributions.

This would enable us to prioritize specific groups for which we know, that data quality has been an issue. When implementing this change, we could easily add futher iterations to individual groups (e.g. groups with bad quality after 3 passes and therefore further users should have a look at them.). At the same time groups with a high quality would not be affected. Implementing this new feature would therefore help us a lot in addressing MapSwipe data quality issue and would help us to produce more reliable data.

Currently, the following information are stored in firebase for each group of MapSwipe tasks (*distributedCount* and *reportCount* are not used.):

key | value
-- | --
completedCount | 4
count | 99
distributedCount | 0
id | 101
projectId | "13512"
reportCount | 0
tasks | {…}
xMax | "157546"
xMin | "157514"
yMax | "133569"
yMin | "133567"
zoomLevel | 18

This information is requested by the app in [this section of the code](https://github.com/mapswipe/mapswipe/blob/master/src/shared/Database.js#L1514).
```
fetch(`${config.firebaseConfig.databaseURL}/groups/` + projectId + '.json?orderBy="completedCount"&limitToFirst=' + groupCount + '')
```

Finally, when a user completed a group, the information of the respective group is updated. [This happens here](https://github.com/mapswipe/mapswipe/blob/master/src/shared/Database.js#L463).
```
group.completedCount = group.completedCount + 1;
```
Still it would be good to keep this information. But, we should add another transaction which reduces the *MissingCount*. E.g. like this:
```
group.MissingCount = group.MissingCount - 1;
```

These changes would also affect the project import. However, the required action would be minimal. We just need to set the *MissingCount* to a start value, e.g. 3 when creating the groups.

**Comment by gkeller26** [comment]
Maybe I could have a look at that issue. But couldn't we just calculate the missing-count instead of storing it, like: 
`missing.count = group.count - group.completedCount`
or is it because of database accessibility that we need to store it?

**Comment by mathcass** [comment]
@gkeller26 Nice! So to give a little background on what we're trying to solve here. Right now, for each tile (each square on the map), we store the following:

* # of tiles with buildings
* # of tiles with "maybe" 
* # of tiles with bad imagery

Here, the counts that we have are the sum of the counts above. We don't happen to have counts for cases where there were no buildings. Another way to say that is we don't have counts for cases where someone looked at a tile and didn't tap it. 

You're right that one way to implement that would be to go ahead and count how many times someone saw a tile and that might be a better implementation here.

**Comment by laurentS** [comment]
I think this is out of date now with v2.0. @Hagellach37 can you take a quick look, and close this ticket if it makes sense? If not, it might need updating to match the current database format...

**Comment by laurentS** [comment]
I'm going to close this, as v2.0 now implements the storage of results differently, and specifically, we store a result object even when there are no buildings, which allows much more detailed stats. The changes proposed here are not relevant anymore.
