### ISSUE TITLE
Review permissions for Android (and iOS)

### ISSUE THREAD

**Issue by mathcass** [mapswipe/mapswipe#17]
It seems that we're asking for Phone permissions in the mobile app but I don't see a real need for it. 

We should verify that we don't need them and then see about removing them.

**Comment by laurentS** [comment]
Expanding on the original issue, we need to review permissions requested, and minimize as much as possible.
Attached are 2 screenshots on Android 5.1 showing what permissions are required:
![Screenshot_2019-06-25-19-54-33](https://user-images.githubusercontent.com/1745184/60165838-f256c580-97f7-11e9-8b9d-0e88c5d62d41.png)
![Screenshot_2019-06-25-19-54-42](https://user-images.githubusercontent.com/1745184/60165839-f2ef5c00-97f7-11e9-8bc3-8c35ea7ea5c6.png)

**Comment by laurentS** [comment]
At the moment, the newest version of the app on Android request 5 different permissions:
1. have full network access
2. prevent phone from sleeping
3. receive data from Internet
4. Play Install Referrer API
5. view network connections
This is on android 7.1. I am not sure how much less we can do.

**Comment by laurentS** [comment]
@jhenshall can you confirm what permissions are requested on iPhone?

**Comment by jhenshall** [comment]
So (as far as I know), iPhones don't have such granular permissions e.g. network access. At least it's not available in normal user interface. I've checked every privacy permission (e.g. location, camera, etc.) and MapSwipe uses none. There has never been any prompt to grant permissions on the new version.

**Comment by laurentS** [comment]
This is probably as good as we'll get without a lot of work, so I'll close the ticket. Please reopen if you find a specific problem.
