### ISSUE TITLE
Blue tiles consistently appearing instead of images

### ISSUE THREAD

**Issue by jbergmann91** [mapswipe/mapswipe#170]
I've been using mapswipe and very frequently tiles don't load (display blue). For a little bit, i marked them red because they were unreadable, but have since decided to back out and retry. Still, most times, i have tiles that don't load.

I am using a xiaomi redmi go, with a vpn from india over wifi connnection if that helps.

1). I do have the most recent version of the app.
2). Hmm, I don't recall certain projects it is happening for.  What would happen when I get the blue tiles would be one project so I would close out and choose a different project.  Closing and restarting the app would sometimes work.
3). I have tried using the 'clear project bugs' button and it didn't seem to do much differently.

Additional info:
It feels to me as though the imagery tiles aren't loading (for whatever reason).  I say this because the last time(s) it happened, I noticed that sometimes only the first 1/3rd or 1/2 or 2/3 of the tiles loaded, the rest were just blue.  I took the above steps to remedy at that time.

I will send a screenshot the next time it happens.

thanks for making the app.  Please release a degoogled .apk available sometime in the future!

**Comment by jbergmann91** [comment]
@laurentS I couldn't recreate this issue on my own

**Comment by Hagellach37** [comment]
It's probably related to the tiles not coming through. It could be related to network issue (slow internet connection), but also other sorts of problems when loading the tile image from the given url.

**Comment by laurentS** [comment]
It sounds like an unreliable VPN. If tiles were actually not available, the app would show a little crossed out camera icon instead. The fact that they are "blue" (which is really the screen background) implies that the image doesn't finish loading.
I would suggest the user (I know it's not you @jbergmann91 ;) retries with the VPN temporarily turned off. If they can't turn off the VPN for whatever reason, try opening these urls in a browser, from the same phone with VPN on:
- https://ecn.t0.tiles.virtualearth.net/tiles/a032232200223002233.jpeg?g=7505&mkt=en-US&token=AopsdXjtTu-IwNoCTiZBtgRJ1g7yPkzAi65nXplc-eLJwZHYlAIf2yuSY_Kjg3Wn
- https://services.digitalglobe.com/earthservice/tmsaccess/tms/1.0.0/DigitalGlobe%3AImageryTileService@EPSG%3A3857@jpg/18/160258/122808.jpg?connectId=91e57457-aa2d-41ad-a42b-3b63a123f54a
- https://services.digitalglobe.com/earthservice/tmsaccess/tms/1.0.0/DigitalGlobe%3AImageryTileService@EPSG%3A3857@jpg/18/160308/122807.jpg?connectId=91e57457-aa2d-41ad-a42b-3b63a123f54a

See if they load reliably in the browser (reload multiple times after clearing cache), if not, please note the errors you see in the developer tools, and share them here, so we can look further into it. Also, please note if it is limited to a specific project or not.

**Comment by laurentS** [comment]
User fixed the issue by using a different VPN/connection
