### ISSUE TITLE
Scrolling is lagging after a few screens

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#172]
**Describe the bug**
For some tasks (current example is the DRC mapping for MSF), the swiping becomes very laggy after the 6th screen. The app no more reacts properly to usual swipe movements and it is very frustrating to finish the task. However, this does not occur for example within the Philippines mapping task or some other. So maybe it's the imagery? 
(issue reported by a user via email)

**App version**
TO BE CONFIRMED

**To Reproduce**

**Screenshots**

**Smartphone (please complete the following information):**
TO BE CONFIRMED

**Additional context**

**Comment by jbergmann91** [comment]
Adding another user report here:

_Mapswipe is regularly very slow, to the point it is unusable. But not always, sometimes it works ok.
Swiping to the next screen is very hard, you have to try several times. Sometimes with no luck.
Specs:
Nokia 3.1
Android 9
Mapswipe 2.0.2_

**Comment by jbergmann91** [comment]
And again here:

**Comment by jbergmann91** [comment]
For first report:

I have an MI A1 with Android 9 (patch level 1. Dec. 2019), app version is 2.0.2 (Updated on 12. Dec). It occurred for two projects -- the DRC mapping task as reported, but I don't remember which one was the other.

**Comment by laurentS** [comment]
Fixed in 2.0.4. @jbergmann91 is it worth emailing the users who reported the issue?
