### ISSUE TITLE
Go Back for Change Detection

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/mapswipe#180]
**Describe the bug**
There is no way to go back if you make a mistake for the change detection project type

**App version**
all

**To Reproduce**
Just map a change detection project type. After swiping the first image there is no way to see and correct your classification for this one.

**Additional context**
If you made a mistake like accidentally swipe left instead of right. There is no way to go back an correct the mistake,. One of the advantages with other project is the ability to go back and adjust.  this a big issue with this new project as a) we are use to been able to go back b) it makes you worry about your selection as you can't go back a fix mistakes.  I actually will unlikely do this new project type without the ability to go back up and adjust, as I don't want send in information that I know is a mistake even if just 1 in hundred swipes.  My suggestion is use swipe up to go back and redo.

**Comment by laurentS** [comment]
This is solved by the new design for CD. Can be closed once deployed to production

**Comment by laurentS** [comment]
Implemented in 2.0.4
