### ISSUE TITLE
Capitalise app name on iOS

### ISSUE THREAD

**Issue by jhenshall** [mapswipe/mapswipe#196]
**Describe the bug**
The app name is all lowercase on iOS home screen rather than capitalised as MapSwipe. This has been fixed in the dev version of app but not prod.

**Screenshots**
![IMG_4729](https://user-images.githubusercontent.com/6359748/79974495-56d2c780-8491-11ea-8865-ddec63a55325.jpeg)

**Comment by laurentS** [comment]
I think this is done by now. @jhenshall please reopen if I'm mistaken.

**Comment by jhenshall** [comment]
Yup, confirmation all done.
