### ISSUE TITLE
Experiment with reference to groups/completedCount

### ISSUE THREAD

**Issue by mathcass** [mapswipe/mapswipe#21]
Here, https://github.com/mapswipe/mapswipe/blob/9eccda71084b8494e2d0d7756f9cfe957825ec67/src/shared/Database.js#L463
we're incrementing the completedCount by of a reference to the particular group. We should update this so that it's a reference to the completedCount instead

**Comment by laurentS** [comment]
This is not relevant anymore, with the new database format introduced in v2.
