### ISSUE TITLE
tutorial text is not correct after 6-7 screens on wide phones

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#218]
**Describe the bug**
On a wide phone (wide/short screen), the prompt shown in tutorial mode becomes incorrect after 6 or 7 screens.
This is in built_area projects.

**App version**
2.0.3(7)-beta

**Screenshots**
If the problem is visual, please add a screenshot of what you're seeing, it will make it much easier to understand the problem.

**Smartphone (please complete the following information):**
 - OS: android

**Comment by Hagellach37** [comment]
on my "fat" tablet and with the latest version `2.0.4(0)` this is no longer an issue
