### ISSUE TITLE
completeness project is sticky after swiping 3 screens

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/mapswipe#219]
**Describe the bug**
The app is just super slow after a few screens of the new completeness project type in the dev version of the app.

**App version**
iOS, 2.0.3(9)-beta

**To Reproduce**
Please provide steps to reproduce the problem:
1. Go to project Nuernberg Completeness test - (1)
2. Click on "Map Now"
3. Scroll left to the next screens and see the app becoming really sticky after 3 screens or so untill the end of the group
4. at some point you even reach a point where imagery is not loaded.

**Smartphone (please complete the following information):**
 - Samsung Galaxy Tab A (2018, 10.5)

**Additional context**
The app seems to have a fairly high usage of RAM, on average around 250MB, max to 1.2GB on the tablet.

Things we could try:
* do not use opacity in react-native for image background but in mapbox instead
* reduce group size during project creation
* take another look at the flatlist component

**Comment by laurentS** [comment]
Using the performance monitor of react-native (in developer tools), I can see that the FPS stays above 50 for built-area projects pretty much all the time, even when scrolling too fast to do anything.
In completeness projects, the FPS drops to below 20, I think this is what you are seeing, but maybe with worse numbers.

[this page](https://reactnative.dev/docs/0.61/optimizing-flatlist-configuration) has a few tips about improving the rendering of flatlist. Playing with `windowSize` and `maxToRenderPerBatch` is helping a bit on the FPS counter.

**Comment by Hagellach37** [comment]
After testing on my tablet I can confirm that the `windowSize` parameter has a big effect on the performance.

windowSize={5} --> ~50fps, nice and fast
windowSize={15}  --> dropping to 10% of that (5fps), slow and laggy

**Comment by laurentS** [comment]
This component could be helpful as well: RecyclerView https://github.com/Flipkart/recyclerlistview

or another option could be to test different JS engines on android: https://medium.com/walmartlabs/react-native-memory-profiling-jsc-vs-v8-vs-hermes-1626949a653b

**Comment by laurentS** [comment]
Fixed in 2.0.4
