### ISSUE TITLE
Remove "timestamp" attribute from result objects

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#227]
We store a `timestamp` on the result object which seems to be the exact same as the `endTime` value, what is the point of storing both?

**Comment by Hagellach37** [comment]
Hey,
I think I remember again why we had different timestamps:

* `endTime` refers to the time a user finished the mapping
* `timestamp` refers to the time the result has been uploaded to Firebase (or not?)

At the moment, this is always/mostly the same for us, but these timestamps might be different once we would have an offline functionality.

**Comment by laurentS** [comment]
Related backend issue https://github.com/mapswipe/python-mapswipe-workers/pull/376

**Comment by laurentS** [comment]
I can't really think of the value of knowing when a contribution was uploaded to firebase. We're not interested in tracking users that way. Is there some value to calculate contribution quality or something like that?

**Comment by laurentS** [comment]
Fixed with release `2.0.5(0)`.
