### ISSUE TITLE
Help users when they're stuck on the tutorial

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#228]
Some users have reported not finding the right answer at some point in the tutorial, getting stuck, and probably giving up on it.

The tutorial should include a way to show the correct answer, maybe by highlighting where buildings are. For the built-area projects, this could probably be achieved using the 2 layer tiles that we use for completeness, by building custom tiles that include hints (like a circle around the buildings, or an arrow pointing to them), and turning them on after the user has tried and failed more than once.

Alternatively, the help message could include a link to a webpage that has the solutions with more explanations. This is easier, but feels less convenient.

**Comment by Hagellach37** [comment]
Ideally, we can come up with some mock-ups on how to improve the feedback for the users during the tutorial. 

I think just highlighting the correct answer (e.g. as a thick border or so) or have an overlay like a check mark to show correct and incorrect answers might be easier than showing the actual building geometries

**Comment by forteller** [comment]
Agreed. I got stuck on the first page of the tutorial and had to press random squares to get to the next page. I would also add that it's confusing when swiping left only changes the text and then you have to swipe again to actually go to the next set of images.

**Comment by laurentS** [comment]
@forteller thank you for the report. We're currently working on a big rewrite of the tutorial to take this and other feedback into account. It should be available fairly soon. Stay tuned!

**Comment by laurentS** [comment]
@forteller We've just released version `2.0.7(0)` of the app, which includes the updated tutorial. I'm closing this ticket now, but feel free to comment further with thoughts and feedback.

**Comment by forteller** [comment]
Sounds good. Looking forward to try it when it hits my local app store :)

**Comment by forteller** [comment]
Finally the new version came yesterday! A bit of feedbak:
- Looks very good! So much better!
- Maybe have more than one example of how buildings look from the sky? Or at least be more clear that that's just an example and they can look different
- On the first page with a test image the infobox on the top covers most of the buildings in the top right box, that you're supposed to find. 
- When selecting the correct two squares the infobox says "you found your first area with"… shouldn't it be "areas"?

Thanks again!

**Comment by laurentS** [comment]
> Finally the new version came yesterday! A bit of feedbak:
> - Looks very good! So much better!

Great! Glass you like it too :)

> - Maybe have more than one example of how buildings look from the sky? Or at least be more clear that that's just an example and they can look different

Yes, changing the text sounds easier. We have also been discussing how to have more than one example, but haven't come up with a very good idea yet.

> - On the first page with a test image the infobox on the top covers most of the buildings in the top right box, that you're supposed to find. 

Good point. We don't actually advertise it, but you can tap the textbox and it will move out of the way. That being said, i think we should change the example so that you don't need to move the box.
@Hagellach37 

> - When selecting the correct two squares the infobox says "you found your first area with"… shouldn't it be "areas"?

Sounds right! I'll open separate tickets for these points. Hopefully somebody sends us a PR ;)

> Thanks again!

**Comment by jhenshall** [comment]
Thanks for all the feedback @forteller ! Really great to hear and agree we need to review. Thanks for opening new ticket @laurentS .
