### ISSUE TITLE
Statusbar progress unreadable

### ISSUE THREAD

**Issue by habi** [mapswipe/mapswipe#23]
I submitted [this bug](https://github.com/mapswipe/app-feedback/issues/34) a while ago.
The problem seems to be here: https://github.com/mapswipe/mapswipe/blob/9eccda71084b8494e2d0d7756f9cfe957825ec67/src/shared/views/Mapper.js#L529, but I have no idea what I would need to change to actually submit a pull request...

**Comment by laurentS** [comment]
Screenshot from original issue

![screenshot](https://cloud.githubusercontent.com/assets/1651235/20435911/31f56692-adae-11e6-94d4-c00adcbc4ecc.jpg)

**Comment by habi** [comment]
Thanks for moving the issue.
