### ISSUE TITLE
Back to level 1, -247km²

### ISSUE THREAD

**Issue by mart-e** [mapswipe/mapswipe#25]
Hi,

I recently reinstalled the app on my phone.
I logged in with my account, I was already level 5.
After a few swipes, I see I am back to level 1 with a negative numver of swipes remaining.
Any idea?

![img_20180729_183035](https://user-images.githubusercontent.com/564822/43368513-6db48324-935e-11e8-9bdc-deb4aac6df3c.png)

**Comment by ericboucher** [comment]
@mart-e thanks for letting us know, we'll look into it!

**Comment by mart-e** [comment]
FYI, I made another long session, enough to get to the level 6 and it was back to normal.
I will let you know if I can trigger again the bug.
Don't hesitate if you need more information.

**Comment by laurentS** [comment]
Closing as level definitions have been updated and calculation now seems to work ok.

**Comment by mart-e** [comment]
Thanks for the follow up, I will let you know if I still have the problem

**Comment by neogeomat** [comment]
hi still a problems,

Stats line up, but level and level bar is reset to 1.
