### ISSUE TITLE
Inconstitency in error messages for password and username length

### ISSUE THREAD

**Issue by kmpoppe** [mapswipe/mapswipe#254]
Good afternoon,

while reviewing the German translations in transifex, I stumbled upon an inconsistency between the English text
"Password must be **more than** 6 characters" and the German translation "Dein Passwort muss aus mindestens 6 Zeichen bestehen" (which means literally Password must be **at least** 6 characters).

Likewise, the Username messages are in the same pattern, just with 4 characters.

Now, in code, `showUsernameError` is set to true if the length of the text is **less than** 4:
https://github.com/mapswipe/mapswipe/blob/b4fa74f268fc6e3c81187a8589b132c3e3b5f73f/src/shared/views/Login.js#L394
`showPasswordError` is set to true if the length of the text is **less than** 6:
https://github.com/mapswipe/mapswipe/blob/b4fa74f268fc6e3c81187a8589b132c3e3b5f73f/src/shared/views/Login.js#L449

The code would imply, that the password (username) must be **at least** 6 (4) characters, not **more than**.

I would suggest to change the messages accordingly.

**Comment by kmpoppe** [comment]
Bump @jhenshall and @laurentS for a comment :-)

**Comment by laurentS** [comment]
Good catch @kmpoppe ! I've just fixed the code based on your report.

**Comment by kmpoppe** [comment]
You didn't associate a PR with this Issue, but I guess it's fixed in 2.0.4(3)-beta now, right?
The Issue would be free to close then.
