### ISSUE TITLE
Add support for private projects

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#264]
This is the frontend counterpart to https://github.com/mapswipe/python-mapswipe-workers/issues/392

The app needs to show private projects, initially instead of public ones. In the future, we might add an option for project managers or team managers to allow showing both private and public projects, but this would require highlighting them differently so it is clear to users what is what.

This ticket only requires checking if the user is part of a team, and adjust the query to the server if so.

**Comment by Hagellach37** [comment]
I agree, for this stage we should only show the projects which are set up for the team the user is a member of. This will avoid a lot of trouble.

**Comment by laurentS** [comment]
Fixed with release `2.0.5(0)`.
