### ISSUE TITLE
Setup app translations

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#31]
The app should be available in more than just English. We should ideally use https://transifex.com as a translation platform, as it is already the one used by the HOT/OSM communities (for instance for learnosm.org)

There are a few translation libraries for react-native, but none seems like a direct match for transifex.

My first research brought up the following thoughts:
- we could use react-native-language to select the language from the phone's settings
- https://github.com/i18next/react-i18next seems a good candidate for localization, despite a heavy bias towards using locize.com for actual translations. It looks like file formats are compatible with transifex though, so setup should be fairly easy
- https://github.com/yahoo/react-intl is another option, though it looks like it results in very heavy code
- https://ttag.js.org looks cool and plugs into very well established gettext tools, but only has a very small community so far

**Comment by reno38** [comment]
"The app should be available in more than just English." Yes! a French version for example !
"We should ideally use https://transifex.com as a translation platform," Yes, I have an account ! 
"as it is already the one used by the HOT/OSM communities (for instance for learnosm.org)" Yes, yes, I'm working on it already!

**Comment by KovalevArtem** [comment]
The issue with the localization of the interface has not yet been decided?

I am ready to help in the translation into Russian.
You can use Weblate. It is completely free for open source projects.
(This service is much more convenient than Transifex. In addition, he has open source!
For example, this service uses [OsmAnd](https://hosted.weblate.org/projects/osmand/))

**Comment by laurentS** [comment]
Fixed with release `2.0.5(0)`.

**Comment by KovalevArtem** [comment]
MapSwipe website
https://www.transifex.com/mapswipe/mapswipe-website/

MapSwipe app
https://www.transifex.com/mapswipe/mapswipe-app/

**Comment by laurentS** [comment]
Instructions for translators can be found here: https://github.com/mapswipe/mapswipe/wiki/Translating-MapSwipe
