### ISSUE TITLE
Use OSM to login to mapswipe app

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#35]
Currently MapSwipe requires creating login and password. Missing Maps project is tightly coupled with OpenStreetMap project so it would easier for OSM users if MapSwipe could use OSM login.

(moved from https://github.com/mapswipe/app-feedback/issues/30)

**Comment by laurentS** [comment]
Comment from @harry-wood on the other repo:

> I agree it would be good to offer OSM login as an alternative (dinky little button).
> 
> A lot of OpenStreetMap mappers might like to use that. It's worth noting that the real power of MapSwipe is to get people on board who are not already OpenStreetMappers (often because editing OpenStreetMap is too complicated). Even so I think this is a sensible thing to have as an option.

**Comment by laurentS** [comment]
Docs: https://wiki.openstreetmap.org/wiki/OAuth
code example: https://github.com/osmlab/osm-auth

**Comment by forteller** [comment]
I agree, and I was uncertain when I opened the app for the first time, whether I should log in with my OSM credentials or not. Before this is implemented, maybe there should be a short text informing you that you can not log in with your OSM account on the login screen?

**Comment by Hagellach37** [comment]
adding this link here which might become useful when we want to link an OSM account to an existing MapSwipe account: https://firebase.google.com/docs/auth/web/account-linking

**Comment by laurentS** [comment]
After discussion with @Hagellach37 today, here are some findings:

[This page](https://github.com/firebase/functions-samples/blob/main/instagram-auth/functions/index.js) shows an example of OAuth login using instagram. Login in with OSM should be fairly similar. It looks like this code should be able to run in a firebase function.

Some auth data would need to be stored in the RealtimeDatabase on firebase (OSM token, OSM user id, firebase user id...) so care must be taken to secure this correctly (permissions...).

Once a user is logged in to their OSM account, we can link this back to a MapSwipe account into which they are already logged in. The way to do this seems to rely on adding extra info to their existing MapSwipe account (OSM user id, OSM auth token), rather then the other way around. Mainly this is dictated by the need to preserve a user's history of contributions in MapSwipe (changing their user id in every contribution would be a ridiculous amount of work, if even possible).

Linking a MapSwipe account with an OSM account does not seem to require both having the same email, as we thought at one point. If the user is able to login to both, then we can link these 2 accounts.

So we would end up with 3 types of accounts:
- `MapSwipe only`: the user only has a MapSwipe account (or has not linked to OSM)
- `OSM only`: the user created their MapSwipe account using OSM OAuth. There is no prior history in MapSwipe
- `Linked accounts`: the user has an existing MapSwipe account, and later links to their OSM account.

Once logged in, the app doesn't really care which type of user they are, unless some feature only makes sense if you have an OSM account.

We still need to map out the user facing workflows for all these combinations, in particular around linking accounts.

Open question, for future extensions:
- can the backend act on OSM (eg. upload a building) on behalf of a user, or does this need to happen in the app?

**Comment by laurentS** [comment]
Another link to firebase docs about using custom auth, basically an overview of what the instagram example above implements https://firebase.google.com/docs/auth/web/custom-auth.

There's not much info on the frontend implementation of this.

**Comment by Hagellach37** [comment]
once this should go live, we also need to make sure to adjust the privacy declaration and say what OSM related information we collect and for what purpose.

**Comment by laurentS** [comment]
As a first step, we will implement a separate signup using OSM credentials, and there will be no way for now to link an existing MapSwipe account to an OSM one. This linking feature will come later, in a separate ticket.

This can be implemented as an extra view in the `Login.js` file, added to the "signup | login | password reset" ones.

- when creating an account with OSM, the user needs to agree to privacy statement before they can tap the "login with OSM" button. In a first iteration, the button is never active unless the checkbox is ticked. In a second iteration, we could store the info client-side, that the privacy policy has been approved.
- mapswipe username will be fetched from OSM username

**Comment by danbjoseph** [comment]
I think this issue should have been closed already. Please comment if not the case.
