### ISSUE TITLE
Show positive feedback also for orange, red and empty tiles

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#37]
The "reward" / "thank you" messages that appear after tapping a few green tiles are great.

Some tasks though have no tile to get tagged green, but still there's effort by the mapper to check that every one of them is either empty (no buildings or roads), a maybe (orange) or the imagery is not readable (cloudy or missing).

This effort should be rewarded in the same or similar way of when the user taps green. Knowing that no buildings are in one area I think it's as valuable as knowing where they are.

(Moved from https://github.com/mapswipe/app-feedback/issues/7)

**Comment by Hagellach37** [comment]
we don't show feedback anymore, sine it was kind of random anyway
