### ISSUE TITLE
0 mappers on all tasks

### ISSUE THREAD

**Issue by forteller** [mapswipe/mapswipe#427]
**Describe the bug**
On the list of tasks all of them say they're being worked on by 0 mappers. 

**App version**
2.0.7 and 2.0.8

**Screenshots**
![Screenshot_20201011-144715_MapSwipe](https://user-images.githubusercontent.com/343561/95679061-b6a06480-0bd0-11eb-9e47-3abe0d503b99.jpg)

**Smartphone (please complete the following information):**
 - Device: SGS7
 - OS: Android 8

**Comment by laurentS** [comment]
Thanks for reporting this @forteller , it's actually a backend problem, which is tracked [here](https://github.com/mapswipe/python-mapswipe-workers/issues/420)

I'm going to close this ticket in favour of the other one. It should be fixed soon.
