### ISSUE TITLE
New firebase data privacy setting

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#485]
We received an email from google that I'll summarise as this:
> As of January 28, we have a new setting to stop sharing personal data from firebase with other google services.

This seems to have been added in response to the Apple privacy information they recently added to the app store, which probably made a lot of apps look really bad (including MapSwipe).

I think we should turn off every data sharing option we can, as I don't see any value in MapSwipe serving the needs of advertisers.

More information is available on google's firebase docs https://firebase.google.com/support/privacy#firebase_service_data but in their usual style, it's fairly terse, and not very explicit about what is actually happening.

@Hagellach37 @jhenshall @jessica-bergmann91 I think we should discuss this soonish, but I see no technical downsides to turning off data sharing, besides the fact that we might not be able to see some details in the analytics, like gender breakdown, or user's interests.

**Comment by jhenshall** [comment]
Sounds great to me, totally agree we should just do it. Wonder if this would be enough to change the options we selected for the Apple privacy declaration. One thing we mentioned before was also removing the advertising identifier. Would this be doing that?

**Comment by laurentS** [comment]
We'll have to read their docs in detail, but I guess that it should allow us to say that the data is not used for anything else than just giving people access to the app's function.
About the advertising id, I suspect we need to change some code to remove it entirely.

**Comment by laurentS** [comment]
#541 removed the advertising ID from the iOS build. We should revisit the appstore privacy declaration, as some answers might have changed for the better.

**Comment by laurentS** [comment]
#556 is probably as close to a fix as we'll come, closing
