### ISSUE TITLE
I Always get the same group

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/mapswipe#49]
This relates to the changes introduced in #47 and #48 

After finishing a group, I get the same tasks again. This might be related to the changes in the back end. In the back end we should query using the `requiredCount` attribute. 

Groups with the highest `requiredCount` should be displayed.

**Comment by laurentS** [comment]
Here's an idea: download N groups to the app, and randomly select one of them to actually use. The data to download isn't more than a couple hundred bytes * N, which should be negligible compared to the volume of imagery.

**Comment by Hagellach37** [comment]
Hey,
I like that idea. It seems to reduce the chance of getting the same group again. I discussed with @Matthias-Schaub another potential option here: https://github.com/mapswipe/python-mapswipe-workers/issues/134

**Comment by laurentS** [comment]
The advantage of this is that it's 2 lines of code. I had a look at your other proposed solutions, which seem more complicated in terms of code to write. Given that there is a limited number of groups to choose from, I think there will always be a (number of groups / numbers of concurrent users) situation where two users get the same group at the same time, or a user sees the same group twice. Any of our proposed solutions will only reduce the likelihood of it. So I'd go for easy to implement :)

**Comment by Hagellach37** [comment]
Hey,
sounds perfect. Let's go for the simple 2-line solution. 
Download a limited number of groups. (Maybe it's even enough to download just the group keys. But that's up to you.) Then select one group randomly to work on. 👍

**Comment by Hagellach37** [comment]
and maybe just one additional question:
* How much effort is it to check the downloaded groups and the groups a users has already finished?

The finished groups should be available from the user profile. A strategy on the app side could be
1. to download 15 groups from firebase 
2. remove the groups a user has already worked on (based on user profile)
3. randomly select one of the remaining groups

**Comment by laurentS** [comment]
I've implemented your suggestion above, and it seems to work ok. There will be an edge case where a user has worked on all 15 groups that have the highest `requiredCount`, which would result in no groups left to work on at a given point in time. While this is theoretically possible, I think the practical risk of this happening is pretty low, so I'd go with it anyway. Maybe you could check what the highest number of groups a single user has mapped in one project is, which would give us a clue as to how likely that case is to happen, but I don't think it's a high priority :)
