### ISSUE TITLE
HU translation

### ISSUE THREAD

**Issue by debyos** [mapswipe/mapswipe#516]
Dear All,
I have [translated the MapSwipe app into Hungarian](https://www.transifex.com/mapswipe/mapswipe-app/language/hu/). You can deploy it.
Thanks in advance

Gábor

**Comment by debyos** [comment]
Hi, I have updated the translation with some new and modified entries. Please, deploy it to the app!
Thanks!

**Comment by laurentS** [comment]
@debyos thanks for the updates! I've just merged your changes, and we're working on a release, but there are a few hurdles in the way.
Transifex opens a PR every time translations are updated, by the way, so there's no need to open an issue.
