### ISSUE TITLE
"Map Further" not working for footprint project

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/mapswipe#53]
When hitting "Map Further" for a footprint project no news tasks are loaded. It's just the MapSwipe Icon which says loading, but nothing happens.

**Comment by laurentS** [comment]
There's a catch in the data loading, so I'm going to temporarily hide the "map further" button, until I have a proper solution.

**Comment by laurentS** [comment]
Note to self, replacing `navigation.navigate()` with `navigation.push()` might help with reloading data.

**Comment by laurentS** [comment]
Fixed in 2.0.4
