### ISSUE TITLE
[building footprint] building extends off screen

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/mapswipe#598]
Device: Pixel 5a
OS: android 12
MapSwipe v2.1.6(2)-beta

Encountered one feature that extended outside the bounds of the view box.

<img src="https://user-images.githubusercontent.com/4806884/144053935-2fe11b67-8ba7-40f4-8209-85ca507ac4ff.png" width="225" height="500">

**Comment by laurentS** [comment]
Fixed in 2.1.8
