### ISSUE TITLE
change separator for progress numbers?

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/mapswipe#601]
android 2.1.6(5)-beta

is a `/` more intuitive or standard for the separator between numbers representing "X of Y total"?  (rather than `|`)

![Screenshot_20211208-161024](https://user-images.githubusercontent.com/4806884/145285981-9c033aae-078d-4e3f-a707-a905b363c744.png)

**Comment by Hagellach37** [comment]
and probably we should start counting from `1/26` and not `0/26`. ;)

**Comment by danbjoseph** [comment]
thanks, it counts from 1 now.
i guess i'm not too worried about `|` versus `/`
