### ISSUE TITLE
better option for icon for "not sure"?

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/mapswipe#602]
android 2.1.6(5)-beta

the "not sure" icon makes me think of a "click for more info" button. 

![Screenshot_20211208-155524](https://user-images.githubusercontent.com/4806884/145287323-199a92e2-1e56-4117-9efb-0cd6564ee8fb.png)

is there any icon that might fit better? maybe something that represents "skip"?

<img width="150" alt="Screen Shot 2021-12-08 at 4 31 56 PM" src="https://user-images.githubusercontent.com/4806884/145287682-bf2f51c2-7b2b-4dab-8d42-7ab98b1efd94.png">

<img width="75" alt="Screen Shot 2021-12-08 at 4 32 52 PM" src="https://user-images.githubusercontent.com/4806884/145287990-a7dede56-cc5d-40af-bca3-b770d0d4c248.png">

**Comment by laurentS** [comment]
This is part of the user testing to be done by @jhenshall

**Comment by danbjoseph** [comment]
its a  "-" with "Not sure" beneath in the release
