### ISSUE TITLE
info modal in footprint mission has bad instructions

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/mapswipe#612]
`Android 2.1.6(7)-beta`

Instructions seen when pressing the top-right info icon inside the app for the footprint mission (screen grab on the left) need to be cleaned up. should match the instructions provided in the tutorial (screen grab on the right)

![Screenshot_20220114-160958](https://user-images.githubusercontent.com/4806884/149585958-a65833c6-56c9-45be-abf1-ce07178d18c3.png) ![Screenshot_20220114-161229](https://user-images.githubusercontent.com/4806884/149585968-79ed785f-5c62-4cf2-873f-85b4a476be49.png)

**Comment by laurentS** [comment]
Can we close this with the changes available in 2.1.8(1)?

**Comment by danbjoseph** [comment]
yes, looks like this is fixed. thank you.
