### ISSUE TITLE
Need to educate people on Missing Maps if using the logo

### ISSUE THREAD

**Issue by adrienbarbusse** [mapswipe/mapswipe#72]
![IMG_4519](https://user-images.githubusercontent.com/32068585/60120709-62723680-9779-11e9-9d47-ecbc74ebc51d.jpg)

There is nowhere I can see on the app anything explaining what missing maps is, and how it's linked to mapswipe

**Comment by jhenshall** [comment]
We've added a brief explanation on the onboarding and now link to Missing Maps website in more info. The use of logo and how we refer to Missing Maps should be considered with UI refresh so closing this as it's own card.
