### ISSUE TITLE
instructions for instructions 

### ISSUE THREAD

**Issue by vmez** [mapswipe/mapswipe#74]
first set of images worked - it had only one building, and swiping left worked.
the second set was tricky because after i selected all possibilities, swiping left didn't work and i was stuck on that page. i tried all possible combinations to see if i had missed a building and i still couldn't move passed it. 

additionally, tapping more than once changes colour gradually to red. this is confusing because they appear in a sequence which tells me the colours might not be related to a mistake that i might have made. 

i tried to find instructions on the screen by taping on the 'i' button but the message was the same as the welcome. it might be good to add more instructions that include for example, how to zoom into a tile, what the colours mean, or an aprox of how many homes am i expected to find.

**Comment by laurentS** [comment]
This is probably fixed with the latest version of the tutorial. If not, please reopen this ticket and we'll look into it.
