### ISSUE TITLE
Building validation missing options

### ISSUE THREAD

**Issue by Filip10** [mapswipe/mapswipe#745]
Please add 2 more option into building validation tasks. "Bad imagery" which is not as much necessary as "Imagery offset". I get in touch with many good mapped buildings with offset. I think they do not belong to "No" category.
After validation someone can select these buildings (mostly ones) and move them to proper position.

**Comment by danbjoseph** [comment]
as of [v2.4.0 of the backend](https://github.com/mapswipe/python-mapswipe-workers/releases/tag/v2.4.0) and [v2.2.6(6) of the app](https://github.com/mapswipe/mapswipe/releases/tag/2.2.6(6)) it is now possible for project managers to create up to 6 custom answer options for validate projects, and each answer option can have up to 6 sub-answer options. we hope to see the projects in the app start to use this functionality soon!
