### ISSUE TITLE
Auth issue on Android 5.1

### ISSUE THREAD

**Issue by vmez** [mapswipe/mapswipe#75]
1) app caused problems downloading on Huawei Android 5.1 
2) asked for permissions that were unseen in other phones
3) when installed, unable to log in - even with an existing account

**Comment by laurentS** [comment]
Permission issues are adressed in #17.

The core of this issue is that it's impossible to signup or login with the app (v1.3.27) on android 5.1.

Download problems seem unrelated to the app (but who knows?).

**Comment by vmez** [comment]
right, tried to download v1.3.27 in another wifi network just in case, and i can't download this version at all on the same Android 5.1

i tried v1.3.26 and worked! i could log in by creating my account. and worked as well when i erased and downloaded the app again. so it had recorded my registration on the first try.

ps. when downloading the app it showed me the same permissions addressed in #17 and it took four attempts before my phone showed it was downloading it even though i had allowed the installation to proceed.

**Comment by laurentS** [comment]
@vmez have you upgraded to MapSwipe 2.x? Are you still seeing this issue?

**Comment by laurentS** [comment]
Closing as it doesn't seem to be an issue any longer. If this is still causing problems, please reopen and provide more details.
