### ISSUE TITLE
prevent crash when project is set to "inactive"

### ISSUE THREAD

**Issue by Hagellach37** [mapswipe/mapswipe#80]
There will be situations, where users will be mapping and a project manager will set the project status to "inactive" at the same time. This currently results in a crash.

the envisioned behaviour:
* after started mapping (user got group from firebase), changes in firebase for this project should not immediately affect my mapping
* after finishing the group the results should be transfered to firebase
* finally the app should "re-connect" to the realtime status of the projects etc.

**Comment by laurentS** [comment]
@Hagellach37 is this still an issue?

**Comment by Hagellach37** [comment]
app is not crashing anymore when I set the status to inactive.
