### ISSUE TITLE
Mapping Page: The sub-options in the Footprint project type is not working (High Priority)

### ISSUE THREAD

**Issue by Shhhhhubh** [mapswipe/mapswipe#800]
## Steps to replicate 
  - Click on a footprint-type project in the mobile app 
  - Click on Map now 
  - In the mapping screen, go to the sub-options and select an option 
  
## Expected Outcome 
  - The page should change and go to the next page 
 
## Actual Outcome 
  - Nothing happens, i.e., the page does not change

**Comment by Shhhhhubh** [comment]
https://github.com/mapswipe/mapswipe/assets/117332528/141cc60f-46a9-4d04-ae56-73406afac7db

**Comment by samshara** [comment]
@Shhhhhubh @udaynwa The issue here is with the `subOptions` field not having a `value` field. We always require the `subOptions` values to have a `value` field. 

We need to set up validation in the mapswipe dashboard to ensure the `subOption` fields always have a value.
I have had a conversation with @shreeyash07 on the issue.

**Comment by Shhhhhubh** [comment]
@samshara dai. The sub-options had value. The validation is also taking place; only the message is not being displayed. Without a sub-option value, the tutorial cannot be submitted.

**Comment by samshara** [comment]
@shubh the `customOptions` for the above project's **Tutorial** is  
```js
[
  {
    "value": 1,
    "optionId": 1,
    "title": "Yes",
    "iconColor": "#2E7D32",
    "icon": "checkmarkOutline",
    "description": "the shape does outline a building in the image"
  },
  {
    "value": 0,
    "optionId": 2,
    "title": "No",
    "iconColor": "#D32F2F",
    "icon": "closeOutline",
    "description": "the shape doesn't match a building in the image"
  },
  {
    "value": 2,
    "subOptions": [
      {
        "value": 3,
        "subOptionsId": 1,
        "description": "If there is cloud coverage"
      },
      {
        "value": 4,
        "subOptionsId": 2,
        "description": "if the area is under shade"
      },
      {
        "value": 5,
        "subOptionsId": 3,
        "description": "if the image is blurry "
      }
    ],
    "optionId": 3,
    "title": "Not Sure",
    "iconColor": "#FF9100",
    "icon": "removeOutline",
    "description": "if you're not sure or there is cloud cover / bad imagery"
  }
]
```
However, for the project `customOptions` we have 
```js
[
  {
    "value": 1,
    "optionId": 1,
    "title": "Yes",
    "iconColor": "#2E7D32",
    "icon": "checkmarkOutline",
    "description": "the shape does outline a building in the image"
  },
  {
    "value": 0,
    "optionId": 2,
    "title": "No",
    "iconColor": "#D32F2F",
    "icon": "closeOutline",
    "description": "the shape doesn't match a building in the image"
  },
  {
    "value": 2,
    "subOptions": [
      {
        "subOptionsId": 1,
        "description": "If there is cloud coverage"
      },
      {
        "subOptionsId": 2,
        "description": "if the area is under shade"
      },
      {
        "subOptionsId": 3,
        "description": "if the image is blurry "
      }
    ],
    "optionId": 3,
    "title": "Not Sure",
    "iconColor": "#FF9100",
    "icon": "removeOutline",
    "description": "if you're not sure or there is cloud cover / bad imagery"
  }
]
```
Here, the `subOption` values don't have `value` field. This is the issue. @shreeyash07 please look into the issue. Perhaps @tnagorra could make it clear.
