### ISSUE TITLE
Upgrade react native from 0.71.3 to latest 0.72.5

### ISSUE THREAD

**Issue by samshara** [mapswipe/mapswipe#811]
```[tasklist]
- [x] Perform react-native upgrade to 0.71.12
- [x] Upgrade react-native to 0.72.3
- [x] Deploy to dev
- [x] Perform tests
- [ ] Deploy to prod
```

### Resources
- https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks
- https://react-native-community.github.io/upgrade-helper/?from=0.71.3&to=0.72.3
- https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v072

**Comment by danbjoseph** [comment]
Thank you for keeping on top of this!
