### ISSUE TITLE
"mission" to "project"

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/mapswipe#812]
new community guidelines mean we are transitioning from "mission" to "project"
this needs to be updated throughout the app

**Comment by danbjoseph** [comment]
also, i am not sure they are used in the app but the types should be matched to the language used on the website
1. find
1. validate
1. compare

**Comment by kopitek8** [comment]
@danbjoseph 

Is the change only limited to the app or should we update it through MapSwipe (community dashboard, manager dashboard, app)?

**Comment by danbjoseph** [comment]
@kopitek8 please match the terminology throughout the MapSwipe ecosystem
