### ISSUE TITLE
text cut off in validate mission second row options

### ISSUE THREAD

**Issue by danbjoseph** [mapswipe/mapswipe#816]
the "Sure" in "Not Sure" is cut off on my Pixel 5a phone
![Screenshot_20230816-105236](https://github.com/mapswipe/mapswipe/assets/4806884/0d0b8bfe-4dc5-46f6-a3ff-ca12b6f17a4c)

**Comment by Katbaloo** [comment]
Same on Galaxy S20

**Comment by kopitek8** [comment]
We tested the issue after the fix in different screen sized devices and it is working fine. Please let us know if the issue arises again after deployment
