### ISSUE TITLE
TM Statistics problems

### ISSUE THREAD

**Issue by JuanMeloColombia** [mapswipe/mapswipe#821]
I have been unable to visualize the number of mapped buildings and kilometers of mapped roads in the project statistics for a few days now.

![image](https://github.com/mapswipe/mapswipe/assets/118753175/8db2f8c0-fa46-4616-9d5e-371660d39bfc)

**Comment by danbjoseph** [comment]
please add this issue to the repository for the HOT Tasking Manager at https://github.com/hotosm/tasking-manager/
