### ISSUE TITLE
Built Area Tutorial: flash text box when its content changes

### ISSUE THREAD

**Issue by laurentS** [mapswipe/mapswipe#83]
To make it more obvious that the content of the text box has changed, it should flash (or bounce, or have some movement) to make it more obvious that its content just changed, and attract the user's attention to it.

**Comment by jhenshall** [comment]
Another option could be to have screens between each tutorial task - giving feedback on the last task and cueing up the next task. Or a combination of these two ideas? Need to do more user testing!

**Comment by laurentS** [comment]
Irrelevant with new tutorial design. Closing.
