### ISSUE TITLE
Edit group names after being created

### ISSUE THREAD

**Issue by Katbaloo** [mapswipe/mapswipe#837]
Is it possible to build in a way for managers to edit a group name _after_ it has been created?  Right now the only option is to archive it and create a new one from scratch, which isn't ideal.

![Image](https://github.com/mapswipe/mapswipe/assets/109613542/45d85d1c-7e76-4328-a448-a5cac8af0c62)

**Comment by Shhhhhubh** [comment]
The user group name is always unique. To ensure this uniqueness, we employ a mapping with unique IDs. However, when updating a user group, the ID is dynamically regenerated, resulting in the removal of all contributions associated with the user group.

Editing or archiving the existing user group and creating a new one are equivalent actions.

Should we proceed with the development of this issue?

**Comment by Katbaloo** [comment]
Thanks for the further information on this.  If editing the name is the equivalent of creating a new group (and losing all the user contributions) then no, we do not want to proceed.

**Comment by kopitek8** [comment]
Closing this issue with a comment:

- Not proceeding with this issue as per @Katbaloo's confirmation
