### ISSUE TITLE
Community statsboard not working

### ISSUE THREAD

**Issue by Katbaloo** [mapswipe/mapswipe#848]
it looks like we still have something going on with the stats.  Something appears to be broken as we are seeing inconsistent and incorrect results.

ie. for my personal user stats ([katbaloo](http://community.mapswipe.org/user/kBa3j56BxJYflKZoyGi4ckDqcb63/)) nothing appears at top banner for total swipes or total time spent (default filter is this year with no swipes).  If i change filter to last year, stats appear below, but the top banner ones are still blank.  [AmRC group page](https://community.mapswipe.org/user-group/-NL6WXPOdFyWACqwNU2O/) is showing top banner stats as well as few other group pages that I check [Lenovo](https://community.mapswipe.org/user-group/-NOGOvhvvyYGFSRjj_v6/), [Microsoft](https://community.mapswipe.org/user-group/-NOyTo2zuMtyCNGaqb6J/), [HP Inc](https://community.mapswipe.org/user-group/-NMeKQhO6zXP0j5ehnDE/).    Back to individual users: [Jorieke](https://community.mapswipe.org/user/hOOHtw9rijUYLIAPDwC9XEObvt13/) (has 2024 stats but not top banner), JoriekeMSF (has no 2024 stats and no top banner, but if you filter for last year, you get top banner stats).
And finally....  all of above for individual users is inconsistent.  I just looked at my stats page again (both for this year and last year) and the top banner stats appeared briefly but now are gone again.  same with some other spot checks against other individual users.
```[tasklist]
### Tasks
- [ ] https://github.com/mapswipe/mapswipe/issues/845
```

**Comment by puranban** [comment]
Hi @Katbaloo 

The issue arises from the  Apollo Client's caching mechanism where the absence of a unique identifier (ID) in the queries related to user stats. Adding the ID as a unique identifier would likely resolve this problem, allowing Apollo Client to correctly cache and manage the fetched data.

@thenav56 Please take a look at the following listed queries:-

```
query MyQuery {
  userStats(userId: "") {
    # Missing unique identifier so add id
    id
    statsLatest {...}
    stats {...}
    filteredStats {...}
  }

  filteredStats {
    # Missing unique identifier so add id
    id
    areaSwipedByProjectType {...}
    contributorTimeStats {...}
    organizationTypeStats {...}
    projectGeoContribution {...}
    swipeByProjectType {...}
  }

  communityStatsLatest {
    # Missing unique identifier so add id
    id
    totalContributors
    totalSwipes
    totalUserGroups
  }

  communityStats {
    # Missing unique identifier so add id
    id
    totalContributors
    totalSwipes
    totalUserGroups
  }
}
```

cc: @kopitek8
