### ISSUE TITLE
Group name not showing up in app (is showing in web ver)

### ISSUE THREAD

**Issue by Katbaloo** [mapswipe/mapswipe#855]
Capturing this issue posted in slack from CRC.
https://mapswipe.slack.com/archives/C0HCW2CJJ/p1720116207016849

If it is an accent issue then we should figure out how to support them in group names

![Image](https://github.com/mapswipe/mapswipe/assets/109613542/33c16322-d816-4814-acfd-bb1f2f88e9f7)

![Image](https://github.com/mapswipe/mapswipe/assets/109613542/89602cc4-46fd-476d-8092-c5d299a53fb2)

**Comment by kopitek8** [comment]
## Investigation Finding

The issue is with the search text input. Instead of a normal apostrophe ('), the user is searching with a tilted apostrophe (’)

## Verdict

Not a bug

**Comment by danbjoseph** [comment]
There is also unexpected behavior (when searching on desktop Firefox) 
<img width="352" alt="Screenshot 2024-07-09 at 7 36 01 AM" src="https://github.com/mapswipe/mapswipe/assets/4806884/80211283-2547-4a0c-a704-e4fe53297c8f">
<img width="291" alt="Screenshot 2024-07-09 at 7 35 26 AM" src="https://github.com/mapswipe/mapswipe/assets/4806884/d1867098-80b2-487e-85e9-df028756f170">

Seems like maybe we should not have allowed certain special characters? The general user will probably have no control over normal apostrophe (') versus tilted apostrophe (’) - rather it will be automatic formatting where they are inputting text.

**Comment by Katbaloo** [comment]
@kopitek8: Would be good to hear thoughts on Dan's comment AND on recommendation moving forward.  It's unclear to me if we are 1. telling people/groups not to use special characters or 2. is there a way (looking forward) we could accomodate special characters?

**Comment by kopitek8** [comment]
@danbjoseph Thanks for pointing that out. It seems like there's an issue with the data rendering in the Community dashboard. We will create a fresh new issue for this and fix it. 

@Katbaloo Accommodating special characters can be very trickly to implement as different languages have different keyboards special characters and styles (we checked in French). Hence, as a workaround, we would recommend adding a warning banner while creating groups to keep in mind using special characters. How does that sound?

**Comment by kopitek8** [comment]
@Katbaloo 

We have fixed the data issue. However, we still need to fix it in the backend as well as the frontend. 

We have created a fresh issue here: [#956](https://github.com/mapswipe/python-mapswipe-workers/issues/956)
