### ISSUE TITLE
Verify Google Play Console developer account

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/mapswipe#870]
**_Creating an issue to track progress for a Slack message sent to @jhenshall by @thenav56_** 

We also noticed this message in the google play console. Do you know how we can resolve this?

> All developers must complete account verification to comply with the updated [Play Console Requirements policy](https://support.google.com/googleplay/android-developer/answer/10788890). If you do not complete account verification by September 12, 2024, your developer profile and apps will be removed from Google Play.
Only the account owner can verify this developer account

![Image](https://github.com/user-attachments/assets/2c63652e-6cdf-4933-a4ea-f2ec3d8df461)

**Comment by jhenshall** [comment]
Just to confirm that this has been flagged with the account holder who has it in hand but just confirming some new details before they can complete it. No worries for the 12th Sept deadline though - all BRC apps depend on it, so it won't be forgotten.

**Comment by jhenshall** [comment]
All done!
